#### 연습 문제
1. data 폴더 안에 rating_train.csv 파일을 로드
2. 결측치를 제외
3. id 컬럼 제외
4. 중복 데이터 제거
4. train 데이터를 생성하기 위해서 label이 0인 데이터중 2000개를 추출
5. label이 1인 데이터중 2000개를 추출
6. 5번 6번의 결과를 단순 행결합
7. train, test 데이터셋을 8:2의 비율로 나눠준다.
8. tokenizer는 Okt를 사용
9. 불필요한 품사를 제외 (사용할 품사 : 명사, 동사, 형용사, 부사, 파티클)
10. 글자 수의 제한은 2자리부터 가능
11. tfidf를 사용하여 벡터화
    - min_df = 3
    - ngram_range = (1, 2)
12. 로지스틱회귀 모델을 사용하여 벡터화한 데이터에서 학습, random_state만 42로 고정
13. test 데이터셋을 이용하여 검증후 평가지표
14. 예측 결과, 원본의 데이터셋과 예측 확률을 하나의 데이터프레임으로 생성
15. 결과물 제출 -> 평가지표, 14번의 결과에서 상위 5개

In [2]:
import pandas as pd
from konlpy.tag import Okt
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv("../data/ratings_train.txt", sep='\t')
df.head()

         id                                           document  label
0   9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        150000 non-null  int64
 1   document  149995 non-null  object
 2   label     150000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 3.4+ MB

In [5]:
import numpy as np
df['document'] = df['document'].str.strip()
df.dropna(inplace = True)

In [6]:
df.drop_duplicates('document', inplace=True)
df.drop('id', axis=1, inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 146182 entries, 0 to 149999
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   document  146182 non-null  object
 1   label     146182 non-null  int64
dtypes: int64(1), object(1)
memory usage: 3.3+ MB

In [8]:
df_0 = df[df['label'] == 0].sample(n=2000, random_state=42)
df_1 = df[df['label'] == 1].sample(n=2000, random_state=42)

In [9]:
df = pd.concat([df_0, df_1], axis = 0).reset_index(drop = True)

In [10]:
x = df['document'].values
y = df['label'].values

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size = 0.2, random_state=42, stratify = y
)

In [12]:
okt = Okt()

In [13]:
def my_tokenizer(text):
    allow_pos = ['Noun', 'Verb', 'Adjective', 'Adverb', 'KoreanParticle']
    
    # 형태소 분석 및 품사 태깅
    tokens = okt.pos(text, stem=True) # stem=True를 통해 어간 추출 (예: '먹었다' -> '먹다')
    
    # 10. 글자 수 2자리 이상 + 지정된 품사 필터링
    # 이전에 질문하신 '무단', '전재' 등 불용어 제거를 여기에 추가할 수도 있습니다.
    result = [word for word, pos in tokens if pos in allow_pos and len(word) >= 2]
    return result

In [14]:
tfidf_vec = TfidfVectorizer(
    tokenizer = my_tokenizer,
    ngram_range = (1, 2),
    min_df = 2
)

In [15]:
X_train_tfidf = tfidf_vec.fit_transform(X_train)
X_test_tfidf = tfidf_vec.transform(X_test)

c:\Python310\lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [16]:
# 생성된 피처의 개수
print(len(tfidf_vec.get_feature_names_out()))

3905

In [17]:
model = LogisticRegression(random_state = 42)
model.fit(X_train_tfidf, y_train)

LogisticRegression(random_state=42)

In [18]:
pred = model.predict(X_test_tfidf)

In [19]:
prob = model.predict_proba(X_test_tfidf)

In [20]:
pd.DataFrame(list(zip(
    X_test, pred, prob
)))

,0,1,2
0,최고의 sf 영화... 말이 필요없다,1,"[0.08639065283036151, 0.9136093471696385]"
1,귀엽고재밌었어요!!! 2005년에는 내용이 아직 받아들이기 힘들었나봐용,1,"[0.24891868621129076, 0.7510813137887092]"
2,99분의 시간이 짧음에도 불구하고 지루함이 느껴진다..,0,"[0.6751904451576521, 0.32480955484234786]"
3,사스가...노무라 만사이 최고의영화,1,"[0.10667823404965138, 0.8933217659503486]"
4,"다시보고싶은영화,여러군데 찾아다녀도 없네ㅠ.ㅠ",1,"[0.415077135397084, 0.584922864602916]"
...,...,...,...
795,명작 입니다 꼭보셔야합니다 꼭보세요 꼭 돈내고보세요,1,"[0.21822844963631882, 0.7817715503636812]"
796,이런게 왜 9점대야...?,0,"[0.6091796410650361, 0.39082035893496386]"
797,나쁘진않네요,1,"[0.4874505841818927, 0.5125494158181073]"
798,"주윤발의 연기력은 볼만하나 지금 보기엔 스토리나 연출력이 영,.~아냐",0,"[0.7790220633324592, 0.22097793666754081]"
799,3부까지밖에 없는게 아쉬울뿐,0,"[0.6857496738788814, 0.3142503261211186]"

In [21]:
# X_test, pred, proba 3개의 데이터를 반복문을 통해서 반복 실행 -> 2차원으로 새로운 데이터를 구성
data = []
for review, value, prob in zip(X_test, pred, prob):
    # value는 1이라면 '긍정', 0이라면 '부정'
    value = '긍정' if value == 1 else '부정'
    # prob -> 둘중에 큰 값만 사용 -> 100을 곱한다. -> 소수점 3번째 자리에서 반올림 -> '%' 붙여준다.
    prob = round(max(prob) * 100, 2)
    prob = str(prob) + '%'
    # review, value, prob 데이터를 하나의 리스트에 대입
    data.append([review, value, prob])
data

[['최고의 sf 영화... 말이 필요없다', '긍정', '91.36%'],
 ['귀엽고재밌었어요!!! 2005년에는 내용이 아직 받아들이기 힘들었나봐용', '긍정', '75.11%'],
 ['99분의 시간이 짧음에도 불구하고 지루함이 느껴진다..', '부정', '67.52%'],
 ['사스가...노무라 만사이 최고의영화', '긍정', '89.33%'],
 ['다시보고싶은영화,여러군데 찾아다녀도 없네ㅠ.ㅠ', '긍정', '58.49%'],
 ['좋너', '긍정', '88.27%'],
 ['진짜 ㅋㅋㅋㅋ개노답 아오빡쳐', '부정', '51.7%'],
 ['부인의불륜을 남편이 정리한 영화인것같군요.그이상 모가있을까요?', '부정', '50.78%'],
 ['감사합니다 덕분에 안보고 잡니다.', '긍정', '58.81%'],
 ['23세 여자임ㅋㅋ영 아이 영화인줄알았는데 완전꿀잼♥ 평점 왤캐낮은지 이해불가...ㅋㅋ캐릭터도넘귀엽고 웃겨서 좋았음 이런영화 너무좋다ㅠㅠ',
  '긍정',
  '85.29%'],
 ['여자들이 보기에나 좋은 영화인듯 동물 좋아해서 봤는데 중반부터 여자주인공 시작부터 끝까지 짜증내는것만나오네',
  '부정',
  '53.47%'],
 ['이런 형편없는 영화에 3500원 지출하여 30분 감상에 눈물을 머금고 포기.', '부정', '58.73%'],
 ['광신도들에의해과대평과받은영화라고나 할까? 참고로 모태신앙인.', '부정', '67.23%'],
 ['다른직업 찾아보길 권장합니다', '긍정', '50.5%'],
 ['웃기기는커녕 유치하구 시답잖네.', '부정', '73.51%'],
 ['이게 마블식 헐리웃 액션인가', '긍정', '52.63%'],
 ['영화는 좋은데 성우는 좋지않는다... 일본 성우 목소리 들었다면 완전한 대박을 날것 같았다..내가 보는 애니중에 제일 감동있고 뭔가 신비롭고 표현할수 없는 무엇과가 있다 이 < 천년여우 여우비 >를 보고 난후에..',
  '긍정',
  '66.52%'],
 ['0점조 아깝고 마니너스 점수를 준다. 애당초 머리길이도 다른 두자매가 아떻게 구분이 안가는가? 머리 두피라도 벗겨서 바꾸었나? 임정은이라는 배우는 광대뼈도 나왔는데 밀가루 반죽하듯이 살을 발라 붙였나?',
  '부정',
  '81.98%'],
 ['스토커 듣다가 궁금해서 봄 ㅋㅎ', '긍정', '50.89%'],
 ['더러운 영화 더러운 감독 어린 이상아씨 너무 불쌍하네요지금같으면 감방갈 일이다. 내 다시는 임권택 감독 영화 안볼것이다. 어디 어린학생을 협박해 그따위 양화를 찍냐 에 퉤퉤',
  '부정',
  '67.99%'],
 ['유작이 너무나 별로다', '부정', '74.99%'],
 ['70년대 영화라는게 믿겨지지 않음재밌어요 내가 중학교때 케이블에서 봤음', '긍정', '76.36%'],
 ['제니퍼 이런 영화에 자꾸 출현하니까 영화인생이 꼬이는거 아닐까? 연기력도 안늘고', '부정', '56.21%'],
 ['암튼 어설퍼.. 정말 노답 노잼..', '부정', '71.72%'],
 ['모처럼 재미난 드라마를 만났네요동시간에 즐겨보던 기황후도 접고 우사수에 완전빠졌어요.톡톡튀는 빠른전개가 잠시도 지루할틈이 없이 빠져보게되네요유진씨 정완캐릭터 어색함없이 잘표현해서이젠 진정한연기자로 자리잡은듯~엄태웅씨도 멋지네요 화이팅!',
  '긍정',
  '60.57%'],
 ['인내심을 조롱하는 지루한 전개의 연속과 맥빠지는 갑작스런 결말...', '부정', '74.32%'],
 ['꿈이란 , 행복의 다른이름..', '긍정', '66.01%'],
 ['시사회 보고 왔습니다... 영화를 만들다 만거니??? 너무 기대를 하고 봤나보다.. ㅠㅠ', '부정', '51.69%'],
 ['감독만이 판타지속에서 울부짖고 있다.', '부정', '65.59%'],
 ['네이버평점과 나와는 코드 안맞는게 너무 많아... 그래서 난 11점 줄래...', '부정', '80.41%'],
 ['ssi bal.이게 영화여, 돼지똥기름이여.. 니기뮈.1편이 최고여.', '긍정', '84.57%'],
 ["적절한 B급 영화였다. B급 영화임을 전제하에 감상했기 때문에 느슨하게 볼만했다. 다만, '정말 재밌다' 는 아니다. 평점이 너무 저질이기에 올려야겠다.",
  '긍정',
  '72.67%'],
 ['바르뎀의 연기가 굿. 끝까지 고난의 연속이었던 작가의 삶...슬프다', '긍정', '76.19%'],
 ['기대안하고 봣는데 정말 재밌다', '긍정', '87.59%'],
 ['헬렌헌트의 연기가 돋보였다.', '긍정', '58.1%'],
 ['아하ㅡㅡ정말 소유진역 짜증나네여;;무슨말도안되게 머리를뽑지를않나맨날 이상하고어색한연기만하고 글고어머니땜에 모였단 애들도 새며느리도 정말어이가없어여맨날같은내용 제자리걸음 -지ㅂ겹네여',
  '부정',
  '79.37%'],
 ['스토리와 관계 없이 분위기가 참 멋있는 영화', '부정', '60.49%'],
 ['감흥도 없고 밋밋하다.', '부정', '76.48%'],
 ['학교에서 음악시간에 보는데 너무 재밌었어요ㅋㅋ 줄다람쥐들이 짱!!!!!!', '긍정', '83.65%'],
 ['타잔! ost너무 흥겨워서 잼있어요~ 동화로 보는 것도 재미있긴 한데, 만화로 보니 더욱 꿀잼ㅋ', '긍정', '76.24%'],
 ['재밌는데...? 6점대 영화는 아닌듯', '긍정', '66.75%'],
 ['한석규의 원맨쇼 . 코미디도 참 잘해', '부정', '61.42%'],
 ['가정파탄하고 마약하고 불륜을 저지르는 플레이보이. 결국 끼리끼리 만나네.', '부정', '54.46%'],
 ['과유불급. 뭔가 할말은 많은거같은데 정리가 안된듯. 음악은 좋다.', '긍정', '52.14%'],
 ['솔직히 노잼...이건 심햇다고 봄', '부정', '89.81%'],
 ['찡하다...연기자분들 진짜 연기 대단하신듯..', '긍정', '68.46%'],
 ['어쩌자고 이런 영화를 만들었을까.. 필름값이 아깝다..', '부정', '87.02%'],
 ['허세작렬 3류영화', '부정', '61.73%'],
 ['자연 속에서 폭력을 배운 타잔 현실에서는 폭력에 경악하다 즐', '긍정', '52.09%'],
 ['좋은영화입니다 꼭보세요, 특히 의상코디가 인상적입니다', '긍정', '79.52%'],
 ['캐스팅이 너무 아깝다. 공유랑 김정화랑 내가 본 영화 중에 캐스팅 제일 마음에 드는데 내용이 초등학교 교과서보다 유치하다니. 감독이 초등학생은 아닐까ㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅡㅡ2점드려요 공유랑 김정화 진짜 선남선녀',
  '부정',
  '72.54%'],
 ['따뜻한 결말 좋아요 좋아요', '긍정', '85.94%'],
 ['지금도 가끔 다시 본다', '긍정', '83.8%'],
 ['내가 아는 최고의 한국영화. 어느세대가 봐도 공감할수 있는 청춘이란 단어', '긍정', '78.05%'],
 ['이거왜만들다말었어', '부정', '77.61%'],
 ['누구보다 따뜻한 남자가 쿨한 인생을 선택할 수 밖에 없었던 이유.', '부정', '61.29%'],
 ['전쟁,액션, 코믹물 왜 다들 1점 주는 알겠다.', '부정', '68.41%'],
 ['1탄이 더 궁금해졌던 영화.', '부정', '53.1%'],
 ['영화가 끝나고..마지막 장면에서처럼 나도 멍하니......', '긍정', '55.62%'],
 ['평점 너무 후하게 나온거아님? 이게 뭥미 ㅡㅡ', '부정', '82.47%'],
 ['내용 구성은 재미있다, 실제인가 뭐지; 사회, 정치에 별로 관심없는 나는 흥미롭게는 못봤다,..,, 다른영화예스맨이랑 헷갈림 ㅠㅠㅠ',
  '부정',
  '51.59%'],
 ['강동원의, 강동원을 위한, 강동원에 의한 영화', '부정', '57.5%'],
 ['정말... 기대 안하고 보러간건대... 대박이였습니다. 어찌보면 엄청지루하고 시간 안가는 영화일지는 모르겟으나... 집중할수록 점점 빠져드는 !! 무엇보다 마지막이 참 감명 깊었네요',
  '긍정',
  '67.36%'],
 ['이게 한쿡영화의 현실이다', '긍정', '62.56%'],
 ['개 쓰 레 기....누가이리 평점을 높여놨느냐......ㅡㅡz', '부정', '85.26%'],
 ['설마... 를 뚫고 만들어진 속편.', '부정', '66.5%'],
 ['영화가 좀 스토리가 또x이 같음', '부정', '75.32%'],
 ['지루합니다 애들은좋아하네요', '부정', '65.29%'],
 ['마지막이라니 이럴순없어 모처럼 볼만한게 있나 했더니쩝', '긍정', '50.98%'],
 ['다시보기 5회중', '긍정', '58.41%'],
 ['이런영화 왜 만들까 이해가 안감스토리도 없고 러브라인도 없고 노출?그딴거 하나 없고액션?없고 드라마적인 내용도 없고 ...이해가 안감 시간이 아까운 영화',
  '부정',
  '91.26%'],
 ['뭔가 블록버스터의 스케일 영화같긴 한데... 저렴한 느낌이 들지...', '긍정', '50.27%'],
 ['인디의 의미만 있다.', '긍정', '66.44%'],
 ['폴워커가 사라지고 갑자기 갑툭튀가 등장했지만 그래도 꽤 재밋엇음ㅋㅋ', '부정', '60.49%'],
 ['사랑에 관한 갈등을 서슴없이 표현.진실되서 좋다.', '긍정', '81.69%'],
 ['미쳣군 이영화', '긍정', '58.49%'],
 ['신난다', '부정', '53.41%'],
 ['이걸 영화라고... -_-;;', '부정', '61.73%'],
 ['전혀 공감가지 않아 미안할정도..', '긍정', '53.87%'],
 ['내 30분 돌려주셈', '부정', '59.16%'],
 ['질질 끄는 거 빼면 10점 만점 최고!', '긍정', '57.63%'],
 ['너무 재밌게 잘봤습니다.주조연 연기자분들 연기도 다좋았구요.특히 이상윤,구혜선씨 두분 잘어울리고 넘 예쁘게 연기 잘한거 같아요.대사도,ost도 넘 잘어울려 좋았구요^^간만에 맘에 쏙 드는 이뿐 드라마였어요.감사!!',
  '긍정',
  '87.75%'],
 ['반담의 정석', '부정', '53.41%'],
 ['재미없다. 지루하다.', '부정', '94.88%'],
 ['자본은누군가에겐달콤한꿈을또다른반대편의누군가에겐썩은사과같이검게곪은꿈을...', '부정', '53.9%'],
 ['코믹연기랍시고 전반적으로 다들 오버스럽다. 특히 성동일.', '긍정', '51.43%'],
 ['왜봤지 이걸 2시간동안', '긍정', '64.45%'],
 ['혼혈왕자, 2부를 있는 연결고리', '긍정', '62.22%'],
 ['감동도 있고, 일단 배우들의 연기가 하나도 억지스럽지않고 재밌습니다. 두번봤는데도 정말 재밌네요 최근 본 영화중에 가장 여운남는 영화였습니다.강추',
  '긍정',
  '95.88%'],
 ['최고지뭐', '긍정', '97.4%'],
 ['좋은 영화네요.', '긍정', '70.83%'],
 ['마리오랑 루이지가.. 부자 관계~ 젠장~ 이거 15년전에 봤나..', '부정', '53.1%'],
 ['현실적인척하는 비현실적인 영화. 영화자체가 가식이고 연기를 위한 연기밖에 보이지 않는다. 유머는 온데간데 없고 말만 있을뿐.',
  '긍정',
  '52.79%'],
 ['정말 재미있게 보았습니다. 음악의 템포와 편집기술이 두드러진 작품이라 보', '긍정', '87.64%'],
 ['qudvkf123 // 그런데 지금은 똥쓰레기지. 혹시나 이 영화보려는 사람은 어찌하라고', '부정', '70.49%'],
 ['연기 연출 구성 등 모든 박자가 최고, 나의 탑5 중 하나의 영화가 될 것같다. 각자의 생각차가 있다지만 영화를 어떻게 봐야 이런 영화를 8점 밑으로 줄 수가 있는거지?',
  '긍정',
  '73.2%'],
 ['와..진짜 손예진,김갑수 연기력 개 소름 돋는다..', '긍정', '63.36%'],
 ['왠만하면 보겟는데 도저히 안되겟어서 경인선볼꺼임.당신들 그냥 식당에서알바나하심이?', '부정', '81.96%'],
 ['아이들이 봐야 무서워할거같은 영화', '부정', '55.29%'],
 ['정말 수준 떨어지는 영화....이게 코믹영화인가?이건 그냥 OOO 영화다..', '부정', '80.74%'],
 ['이런 쥐..포..같..은..', '부정', '70.51%'],
 ['민영화 되면, 대부분의 사람들은 더 고통받겠지요? 희망이 점점 사라지는 시대가 되는 것 같아, 암울합니다.',
  '부정',
  '59.45%'],
 ['영화 진지하고 스릴있는데 은근히 웃긴장면도 많다..', '긍정', '64.8%'],
 ['끝이허무하지만 연기에 박수를', '긍정', '51.92%'],
 ['난 개인적으로 좋았음 그리고 짬뽕이라는 말도 많던데 그건 이야기를 이을려고 한것같음', '긍정', '60.53%'],
 ['왕가위 영화만 볼만.....-0- 나머지 영화는...........', '부정', '61.73%'],
 ['보면 기절할 영화....넘 재미 없어서....해리슨포드 최악의 영화...', '부정', '87.26%'],
 ['인내력으로도 못 보겠더라. 인물들 모두가 하나같이 안 어울린다.', '부정', '50.01%'],
 ['과연 잘됄까? 다들 우려가 많은 드라마... 그래도 잘됬으면 한다. ㅎ', '긍정', '53.45%'],
 ['이게 뭐냐고 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ', '부정', '53.41%'],
 ['여배우가 좀 이쁘다.. 재밌다는 평점에 속지마라.', '긍정', '65.11%'],
 ['가슴이 아픕니다.', '긍정', '78.58%'],
 ['킴바우어....', '부정', '53.41%'],
 ['얼마나재밌는데..', '긍정', '82.78%'],
 ['뱀파이어 영화중 단연 최고인듯', '긍정', '77.37%'],
 ['일본놈들 짱나네! 백제가 검술,검,갑옷,철기술까지 전수해줬더니 멸망해서 배신하다니', '부정', '57.04%'],
 ['어릴때 본 영화인데 선우일란의 비쥬얼은 요즘 아이돌 못지않음', '긍정', '67.58%'],
 ['배우가 영화를 본 소감이 궁금하다', '부정', '51.24%'],
 ['13년의 제작기간이라서 1점 주러 왔습니다', '부정', '56.6%'],
 ['별하나도 아까움 홍대가믄 저리사는애들 널렸음 무슨영화씩이나만들어 마지막에쳐맞고 입술비비던장면 키스라하기도짜증남 정말 토나올뻔',
  '부정',
  '80.88%'],
 ['이런 잔잔하고 미소를 부르는 영화, 너무 좋아.', '긍정', '78.02%'],
 ['으악!이 당시..이거 빌려놓고 머가먼지 정신없었던 기억이..윽', '부정', '71.67%'],
 ['몇번이나 더 보고도 여운이 가시지 않아 평점을 남기네요.정말.. 정말 아름다운 영화이 말밖에 안나옵니다.. 정말 제 인생의 영화에요',
  '긍정',
  '88.82%'],
 ['알렉산더 페인의 대표작 중 개인적으로는 가장 실망스러웠음..', '부정', '70.85%'],
 ['스토리, 영상, CG 모두 합쳐도 1점', '긍정', '58.24%'],
 ['당구대 앞에서 알파치노의 눈빛연기를 잊을수가 없어', '긍정', '69.35%'],
 ['많은 것을 떠나 한국의 오랜 전통과 문화라는 생각이 듭니다. 문화의 다양함에는 옳고 그름과 우월과 열등함이 없다는 진리가 느껴집니다.진한 감동과 그동안 삶에서 베푸신 사랑과 노고의 따뜻함과 슬픔이 느껴집니다.그리고 어머니께 더 잘해드려야 겠습니다.',
  '긍정',
  '73.25%'],
 ['하나도 안무섭고 새로운거없고 악령이라며 나치가 나오고 어이상실영화', '부정', '71.99%'],
 ['진짜 무슨 70년대 영화 같음, 줄거리든 볼거리든 망작..', '부정', '56.16%'],
 ['재밌었음10자10자', '긍정', '98.06%'],
 ['이거 구라안치고 진짜 유치함. 평점 6~7점이 적당한데 너무 높아 1점줌', '부정', '72.93%'],
 ['재미는 있었는데 포스터가 없었네요...', '부정', '50.42%'],
 ['유쾌하지는 않지만 르네가 나온이유 하나만으로 좋다', '부정', '52.25%'],
 ['똥폼잡는 슈트를 입는다고 다 히어로냐? 니가?', '부정', '62.02%'],
 ['성유리 말투랑 음성 못 고치냐? 어른이면 어른답게,음성이 그게 뭐야!..앵앵거리며..모기같아!..피나는 노력으로 음성부터 변화시켜라!!여자가 음성이 나빠도 팔자 세진다.음성도 운에 속하거든~토크쇼MC 할만한 자질과 언변도 없으면서 욕심이 과했어',
  '부정',
  '69.87%'],
 ['척노리스 작품 중 최고라 해도 될 듯.', '긍정', '84.74%'],
 ['오랜만에 시트콤 몰입하면서봄 캐릭터가 살아있어', '긍정', '58.27%'],
 ['평점낮은거이해안가고올리비아남친일안하는건필요한설정이었죠 올리비아가지금느끼고있는감정상황들을돌아볼때너무도필요했다고보는내내느꼈는걸요 남친돈많은건뒤의일이고거지고실업자였어도 올리비아를정말많이어루만져줬을겁니다 돈밖에없는사람은누군지돌아보길..올리비아는안정이필요했을뿐',
  '긍정',
  '61.2%'],
 ['임권택 감독 영화를 많이 본 것은 아니지만, 이 영화 역시 구성이 탄탄하고 장면마다 상징적 의미가 묵직하고 섬세하게 들어있다.',
  '긍정',
  '64.05%'],
 ['평점이 이해가 안간다 굳굳', '긍정', '54.87%'],
 ['평점 알바들 알바비 받어 니들이나 함 더봐라.10만은 채워야지...ㅋㅋㅋ...알바들도 돈아까워 다시 못보게씨',
  '부정',
  '75.81%'],
 ['임하룡 씨의 어설픈 악역연기~안습', '부정', '63.4%'],
 ['신날 법한 소재인데, 이렇게 심심하게', '부정', '68.2%'],
 ['제이크 연기도 좋았고, 스토리도 몰입감 있었음.', '긍정', '69.81%'],
 ['내가 병장 분대장일때 진짜 저런 이등병 막내 받은적 있는데 이건 이등병놈이 100퍼센트 문제다. 뭐 사회를 탓하고 그럴거없음 그냥 이등병 관심병사가 사람구실 못해서 문제생기는거지',
  '부정',
  '81.47%'],
 ['.............', '부정', '53.41%'],
 ['최고의 드라마. 볼 때마다 많은 생각을 하게되는, 잊을 수 없는 드라마.', '긍정', '86.14%'],
 ['유쾌하게 멋진 영화', '긍정', '82.5%'],
 ['진짜 OOO기다 번역도 쓰레기고', '부정', '77.54%'],
 ['본방사수!!!!ㅁ!!!!', '긍정', '51.31%'],
 ['원작이 진리다 ....', '부정', '70.45%'],
 ['아 솔직히 너무 재미없다.ㅠㅠ', '부정', '69.49%'],
 ['대 실망이야', '부정', '84.69%'],
 ['공블리짱', '부정', '53.41%'],
 ['스캐일만 무지큰 쓰레기 영화', '부정', '86.37%'],
 ['클린트 이스트우드님 영화는 진짜 ...', '긍정', '61.33%'],
 ['왜 평점이 9.11이죠?', '부정', '67.93%'],
 ['당시에는 센세이션했던 영화! 지금도 저예산으로 이정도 퀄리티의 영화는 없다지..이거 조만간 리부트로 만나보고 싶은 영화이기도 하다..',
  '부정',
  '59.19%'],
 ['원작 소설 찾아봤는데 우리나라에는 없네요~ 좀 유치한 맛도 있지만.. 재미난 설정~', '부정', '81.14%'],
 ['에로영화를 보고 싶었다. 하지만 좋은 영화를 찾았다.^^*', '부정', '50.21%'],
 ['10만점을 주겟어요! 아진짜 이거 보고싶은데 어디서 봐야할지 모르겟음.ㅠㅠ', '긍정', '57.93%'],
 ['진심 시즌1은 대박 허니잼이엿는데 2는 땅콩잼이다 그리고 진짜 코우 누님 프로필좀 바꿔라 저게뭐냐 증명사진이냐',
  '긍정',
  '59.1%'],
 ['[쏘우] 이후 가장 애잔했던 죽은 척, 도도한 웃픈 반전.', '긍정', '59.81%'],
 ['원작 소설을 찾아 보고 싶다.', '부정', '63.32%'],
 ['나 혼자힘으로 평점을 존나게 깎을 수 있다니!!', '부정', '54.01%'],
 ['일본사랑영화보면 애들사랑에빠지는속도가 빛을능가함 그냥 처음봐서 사랑에빠지고 좋아해지고 몇번얘기하고 그러면 지목숨까지도 내놓을정도.; 먼가이상함 말하고자하는게먼지도몰겟고 남주냄새는또머임? ㅈㄴ현실정 제로고 막판에 억지감동준거에 눈물낫다는건또먼얘기?',
  '긍정',
  '61.77%'],
 ['인물들 하나하나가 재미있는 영화~', '긍정', '52.73%'],
 ['내용은 점점 산으로 가네...화면 돌려대느라 어지럽고 산만하다.', '부정', '72.29%'],
 ['업소에서 몸파는 거랑 서로 인사만 하는 사이에서 섹파하는 거랑 다른게 뭐고 이 딴 상업성 쓰레기 영화에 평점 가관이다',
  '부정',
  '72.94%'],
 ['이게 옛날 영화라면 이해가 가지만 2014년 9월보고 깜짝놀랬다..', '부정', '57.68%'],
 ['굿닥터 따라하는거 같음..', '부정', '61.43%'],
 ['글쎄요.... 뭐랄까... 영화 제목을 잘못 보고 착각한 내 잘못이랄까...', '부정', '66.78%'],
 ['탄탄한 스토리와 연기자들의 연기가 몰입도 100% 간만에 멋진 드라마 한편 보게되서 감동! & 해피!', '긍정', '80.0%'],
 ['불편하기만 할 뿐인 영화', '부정', '64.45%'],
 ['진짜 개재미 없다..완전 지루함...긴장감 따위도 없다..액션은 개뿔..', '부정', '74.39%'],
 ['방금 티비에서 보고 왔는데 평점이나 반응이 당황스럽다나만 재밌었나..ㅎㅎ나름 괜찮았는데 소소한 재미도 있구 여자지만 김민정도 이쁘고',
  '긍정',
  '79.78%'],
 ['반지의 제왕 주인공의 이미지 변신도 좋고 잔임함은 정말 잘 그려내긴 했는데 역시나 결말이 너무 억지스러웠다. 찜찜한 결말을 위한 결말이였을 뿐.. 머리카락에 집착하는 것도 너무 흔한 소재였고... 차라리 최근에 본 더콜이 더 나은 듯...',
  '긍정',
  '51.53%'],
 ['것참...', '부정', '62.77%'],
 ['넘넘 재밌어욥^.^ 월요일밤 11시 알람까지 맞춰놓고 본방 사수하는 열혈 시청자입니다 ~ 비정상회담 우여곡절도 많지만 비온뒤땅이 굳어지는법... 화이팅하세요!!',
  '긍정',
  '71.43%'],
 ['은퇴작품으로 통수를 후려치는 어느 또라이 작가의 똥', '부정', '60.82%'],
 ['배우의 연기는 엄청나지만, 스토리는 내내 답답하고 결국 새로울 것도 없다. 한국식 막장드라마 같은 답답함을 못 견디는 분들은 절대 보지 말길. 영화 끝나고 감독한테 욕해보긴 또 처음...',
  '부정',
  '79.92%'],
 ['난 잼있던데? 약간 유치하긴했지만...ㅋ', '부정', '68.84%'],
 ['의리가 없다.', '부정', '65.44%'],
 ['카펜터의 괴물을 하이틴으로 버무린 모방품', '부정', '54.63%'],
 ['남들이 안하는짓 하는게 에술이 아니라오', '부정', '68.06%'],
 ['와 ㅋㅋㅋ 나 진짜 ㅋㅋㅋ 대박ㅋㅋ 심각하고 무거운영화일줄알았더니 진짜 완전 깨알재미와 좋은 로맨스까지 ㅎㅎ 너무너무재미있는뎁ㅂ!',
  '긍정',
  '91.58%'],
 ['10년만에 다시봤는데..최고다 막둥이 넘 귀엽다 ㅎ', '긍정', '87.04%'],
 ['광활한 아프리카에서 소녀의 성장기 감동 팍팍', '긍정', '89.72%'],
 ['정말이지애들장난같은작위적스토리는비틀즈에대한오마쥬가아닌능멸이란생각이들정도', '부정', '60.15%'],
 ['영화관에서볼수없어아쉽네요ㅠ', '부정', '64.75%'],
 ['결국 어머니의 사랑을 필요로 했던 케빈', '긍정', '57.79%'],
 ['아무리 시간이 남아돌고 할짓 없으면 차라리 새우깡을 사서 갯수 세어가면서 하늘을 보세요. 절대절대 이 양화보지마셈. 정말 더럽게 재미없음. 지루하고 어설픈 스토리 어설픈 연기력. 최악임억울해서 로그인하고 글 쌈',
  '부정',
  '94.28%'],
 ['반전!!!!반전이 꿀잼..!', '긍정', '77.26%'],
 ['90년대 향수를 불러일으키는 배경도 재밌었고 잡다한 샛길로 새지 않고 확실히 음모론에 초점을 맞춘 스릴전개도 만족스러웠음.',
  '긍정',
  '68.32%'],
 ['하나님의 존재를 철저히 부정하는 사탄과같은영화..개인적으로 보는내내 능욕당하는기분이였다 이렇게 기분나쁜영화는 레퀴엠이후로 오랜만이다',
  '긍정',
  '59.79%'],
 ['배경음악과 존트라볼타의 연기력... 무엇을 더 바랄까??', '부정', '53.98%'],
 ['아..놔....ㅅ ㅂ 시간이 아까워라....', '부정', '94.68%'],
 ['제임스 딘...야동에서마니 본...그 배우???? 헐 ㅋㅋ', '부정', '72.13%'],
 ['재밌고, 슬프고, 아련한 영화', '긍정', '91.96%'],
 ['임신이라네 ㅋ 헤어지니 어쩌느니 할마당에 왼 임신? 그럼대체 어디까지 간다는 예긴지 진짜 막장도 이런막장드라마가 없군 ㅜㅜ',
  '부정',
  '61.76%'],
 ['눈물이 흐른다. 저분들이 있기에 오늘의 우리가 있다', '긍정', '85.02%'],
 ['김민종씨 멋집니다.', '긍정', '80.34%'],
 ['보지마라 형도 진짜진지하다', '긍정', '59.65%'],
 ['무엇하나 분명하지 않은', '부정', '51.7%'],
 ['감독에게 만점을 주고싶다 그 인간쓰레기 같은 권력자들 지들 자식이 이런대우 받으면 무슨생각을할까 지가 한짓처럼 대수롭지않을까 인간은 언제나 죄를지으면 돌려받는다',
  '부정',
  '66.91%'],
 ['남 애기같지 않네(^_^). 옛날엔 다들 이 비슷하게 살았어~~', '부정', '66.1%'],
 ['독립영화 냄새나..', '부정', '52.57%'],
 ['강동원 김정화 짱 ^ ^', '부정', '53.41%'],
 ['그냥 쓰레기임....', '부정', '91.61%'],
 ['잼써요', '부정', '65.68%'],
 ['ㅇㅇ 김예림이랑엘연결하기만해봐ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ', '긍정', '51.96%'],
 ["영화가 끝나고 펑펑 울었다. 그동안 나도 모르게 나와는 조금 '다른' 이들을 '틀리'다고 외면하고. 질타했던거 같다... 깊은 반성을 할 수 있 게 해준..고마운 영화다.",
  '긍정',
  '63.33%'],
 ['평점이 좀 늦었네요^^ 토리코 처음 극장판 엄청 재밌었어요^^ 특히난 GT로봇하고 싸우는 장면이 쵝오였음ㅋ',
  '긍정',
  '66.24%'],
 ['완전 굿. 재밌네요. 이영화 재미없다는 사람은 대체 뭐지?', '긍정', '54.72%'],
 ['1점도 아까운 내 평점 10자', '부정', '90.98%'],
 ['난너무 재밌게봤다!!! 진짜 긴장의연속 ㅠㅠ 슬프다.. 온몸에힘주고봣음 평점낮아서 기대안하고봣는데 기대이상!!!!',
  '긍정',
  '91.76%'],
 ['추사랑네는 그만 하차합시다 너무컷구 식구들위주로나오구 아이들 나오는거지 추성훈시합은 왜나오는거죠.. 별로 궁금하지도않구 경기하는 모습이나오니 좀 그렇더라구요',
  '부정',
  '63.41%'],
 ['당시 정말 재미있게 본 영화임에는 틀림없지만...', '긍정', '83.57%'],
 ['시리중 최고 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ', '긍정', '97.4%'],
 ['1편보다 못하다.', '부정', '64.4%'],
 ['극장판인데 액션이 이 따구냐? 스토리도 이뭐병', '부정', '56.85%'],
 ['나늘 돌아보게 만든 영화. 마지막장면에서 울컥하는 감동이 오네요.', '긍정', '68.88%'],
 ['실제 성행위가 압권임..', '긍정', '56.64%'],
 ['유이가 연기를왜이렇게못해?', '부정', '51.48%'],
 ['왜이렇게 평점높아 이건 영화가아니라 다큐멘타리다', '부정', '86.69%'],
 ['1점도 아깝다 -ㅂ-', '부정', '90.38%'],
 ['니미.. 포스터 OO이 만들어놨네. 포스터와는 달리 킬링타임으로는 A급 영화니 안심하길 보길. 빠즈 베가를 워낙 좋아해서 봤는데 빠즈 베가보다 자넷 맥티어의 연기에 빠졌다. 추천추천',
  '긍정',
  '60.66%'],
 ['뭐지 이 찜찜함..재밌게보다가 허무하게..후편없어으면 이건 아니다..', '부정', '72.81%'],
 ['쓰레기덩어리', '부정', '95.2%'],
 ['모두 남동생의 망상일 수 도...', '긍정', '70.97%'],
 ['가능성에 점수를 주고싶다', '부정', '62.32%'],
 ['좋은 소재와 탄탄하지 못한 스토리', '긍정', '52.5%'],
 ['기대하지 말고 보시길. 안봐도 괜찮은 영화.', '긍정', '57.13%'],
 ['주말에 하는 것중에 유일하게 재밌는 드라마ㅎ', '긍정', '80.32%'],
 ['생각없이쉽게쓴각본. 알맹이없는킬링타임용액션영화.', '부정', '65.0%'],
 ['99년도 허준이랑 내용이며 대사가 너무 똑같애 ㅡㅡ 이런 허준은 전광렬이 짱이다!!', '부정', '77.21%'],
 ['그만했어야지.', '부정', '64.3%'],
 ['2014년 들어.. 보다 꺼버린 영화 그 첫번째.', '부정', '67.85%'],
 ['왜 영점이 없는거야.중국영화는 무작정 10점대 정신차려여.넘쉬운것 같은영화,', '부정', '72.99%'],
 ['중간에 갑자기 막 뛰어넘어서 좀 흐름이 깨졌지만 마지막엔 엠마가 임신했으면 좀 더 슬펐을 듯', '긍정', '68.75%'],
 ['ㅎㅎ 재밌어요^^', '긍정', '95.56%'],
 ['최고 최배달 선생^^ 정말 감동적으로 봤습니다', '긍정', '96.39%'],
 ['재밋냐', '긍정', '72.05%'],
 ['미치도록 끝까지 가는 영화 조이디비젼..이언커티스..최고', '긍정', '74.99%'],
 ['아들을 숨기고 걸어거는 그모습은 아직도 잊혀지지 않는다..', '긍정', '54.4%'],
 ['쓰레기 함부로 버리지 맙시다.', '부정', '93.71%'],
 ['킬링타임으로괜찮음 그리고 여주인공 귀여움 포스터는 안습이지만ㅠㅠ', '긍정', '57.99%'],
 ['고전으로 돌아갑시다', '긍정', '52.71%'],
 ['역지사지. 아이들에게 상대방을 배려할 줄 아는 마음을 키워주는 만화영화. 8.7점', '부정', '50.04%'],
 ['ㅉ', '부정', '53.41%'],
 ['짐 자무시와 조니 뎁의 삶과 죽음에 관한 통찰... 담배는...?', '긍정', '54.88%'],
 ['가끔 생각나는 영화..', '긍정', '53.73%'],
 ['이범수에게 제일 맞는 옷은 이게 아닐까?', '부정', '75.1%'],
 ['마무리가 식상하지만.. 꽤 감동있는영화', '긍정', '73.55%'],
 ['저 줄거리 하이텔 필름스 시절에 내가 쓴 건데...ㅋㅋ', '부정', '56.04%'],
 ['발연기 발각본 발연출의 교과서', '부정', '63.89%'],
 ['이영화 다시 찾구있는데..예전에 고등학생때 극장에서봐서 그런지 공포중에 젤재밋엇', '부정', '50.67%'],
 ['긴장감은 있었으나 영리하지 못한게 큰 단점', '긍정', '68.82%'],
 ['정말 가슴따뜻한 이야기.. 뒤에가서 미친듯이 운영화..ㅠ', '긍정', '84.77%'],
 ['드라마 평을 왜 여기다가 하고있어 ㅉㅉ', '긍정', '52.86%'],
 ['이거 최고임 ㅠㅠ 그 누가 황진이 역할을 이렇게 완벽하게 소화할수있겠는가', '긍정', '75.88%'],
 ['요즘 매주 기대합니다 ^^', '부정', '56.68%'],
 ['말이 필요없는 명작.. 어릴때 본 영화지만 지금봐도 재미있네요', '긍정', '90.83%'],
 ['쓰레기만도 못한 영화. 뻔히 예측가능한 결말과 어설픈 시나리오와 연출력. 배우들이 아깝군.', '부정', '94.1%'],
 ['역대급 개꿀잼. 하 시즌 4 나와라', '긍정', '52.83%'],
 ['쩐다! 진~~~~~~~~~~~~~~~~~~~~~~~짜 재미없어!ㅎㅎ', '부정', '76.81%'],
 ['살다살다 첨으로 평점 남겨봅니다. 80년도에 개봉했으면 잘만들었다고 할만하군요..옥에티도 많고 어이없는 설정과 스토리 배우들의오글거리는 연기..내가해도 잘했겠다....대책없는 허무한 마무리까지 하하하... 시간낭비 제대로다',
  '부정',
  '82.12%'],
 ['씨네21기자들은 네이버 로긴금지', '부정', '62.09%'],
 ['이영화 만드신 감독님께서 긴급조치19호의 감독이었다니 ㅡㅡ;', '부정', '75.28%'],
 ['별로다 해커가 무슨 cctv만 볼줄알고 나머지는 못함', '부정', '79.84%'],
 ['진짜 예전에 재미있었는데 요즘 광휘 때문에 노잼됨. 광희 나가면 안 되요?', '긍정', '54.92%'],
 ['장인의 작품에 몰입을 방해하는 배우들이 있어 안타까워 하다.', '부정', '50.61%'],
 ['재미쪄 ㅎㅎ신민아 짱좋음 ㅋㅋㅋㅋㅋㅋㅋ', '긍정', '75.45%'],
 ['전형적이어도 난 이런 영화가 넘 좋다 행복해지는 느낌!', '긍정', '69.74%'],
 ['리틀 보이 맛을 고새 까먹은 듯^^', '부정', '56.29%'],
 ['느그들은 도대체 영화를얼마나 잘만드가니? 엉?돈꼴랑 마넌 냄서 명화를 바라냐? 염치 잔 이써라 평론가 니네는 3점 조뜨만 허허 점수 짜게조야 니네가 영화에 대해 머짠 아는거 가찌? 똑가튼 밥 먹고 똥싸는 넘들이으디 느그가 영화한번 찌거바',
  '부정',
  '67.66%'],
 ['감독아 뭐니~??언제 무서워해야돼~??너에 의도가 뭐야~??영화 언제 또 찍어~? 알아야 내가 그걸 안 보지~대단해~ 그렇게 사람 짜증나게 하다니~~인정~!!!!',
  '부정',
  '72.82%'],
 ['인도 영화는 모두 뮤지컬인가...', '긍정', '66.74%'],
 ['그나마 fast n furious를 살릴 건 마지막 장면 뿐인가? 다음편의 첫장면이기도 한.', '긍정', '56.93%'],
 ['배꼽잡고 웃었다진짜 ㅋㅋㅋㅋㅋㅋㅋㅋ블랙잭 역시 완전 나의선샤인 ㅠㅠ', '긍정', '75.07%'],
 ['로드리게즈&gt타란티노,ㅋ어쨌든유쾌한B급종합영화세트!TwoAgainstTheWorld', '긍정', '70.31%'],
 ['그 어떤 청춘 스타도 이 영화의 남자 주인공 만큼 빛 나지 않는다', '부정', '68.51%'],
 ['흐흐흐 망했군 망했어~', '부정', '59.15%'],
 ['오랜만에 가족들과 재미있게 본 영화라 더 감동적이었어요', '긍정', '86.79%'],
 ['누구나 결국엔 운다..아버지를 생각하면.', '긍정', '51.96%'],
 ['아직 8화까지밖에 안나온상태지만 보는 내내 눈을 뗄수없게만드는 몰입감, 그리고 긴장감, 배우들의 연기력이 더해져서 2014년 최고의 드라마라고 생각됩니다.',
  '긍정',
  '66.55%'],
 ['스토리도 탄탄하지 않고 아이들이 보기에 여자캐릭터의 모습이 너무 선정적이었습니다 최근에 영화 보면서 졸립긴 처음이었고 최악이었음',
  '부정',
  '63.01%'],
 ['산타의 존재 유무를 떠나 그것을 믿고 싶어하는 순수한 그들을 위한 영화', '부정', '54.01%'],
 ['재밍네', '부정', '53.41%'],
 ['아 졸라무셔ㅋㅋㅋㅋㅋ근데 저 여고생 납치한 살인자뭐냐 ㅠㅠ 잘생겼네 살인범주제에', '긍정', '52.2%'],
 ['억지감동 억지연기 진짜3류다 그나마 우리 귀요미 효진의 발견ㅋㅋ', '긍정', '65.12%'],
 ['연기와 분위기가 장악하여 캐릭터가 스스로 어긋난 행동을 하고 저정도의 반전에 맷이 마음을 바꾼다는 것도. 부사장급이 저러고 다니는 것도. 착한 수가 바로 회사에 맷의 배신을 찌른 것도. 반대입장인 가게주인이 수에게 급호감을 느끼는 것도 전부 개연성없음',
  '부정',
  '58.45%'],
 ['킹재밌음 진짜 이것만큼 재밌는 뱀파이어 영화는드뭄', '긍정', '91.07%'],
 ['생각보다 재미있구만 ㅋ추자현이 굿', '긍정', '91.12%'],
 ['강지환홀릭', '부정', '53.41%'],
 ['지루할 틈이 없다!!!!', '부정', '80.93%'],
 ['정말 최고의 SF영화이다', '긍정', '90.55%'],
 ['영화 개츠비를 보고났을때 느꼈던 것은 돈, 명예 , 욕망 그리고 사랑이 얼마나 덧없고 인정머리 없는 것인지를 똑똑히 느끼게 해주었다. 데이지의 전화벨 소리를 들었을때 순진하게 고개를 들었던 개츠비, 아마도 영화속에서 가장 순수한 인물이 아니지 않을까?',
  '부정',
  '69.61%'],
 ['아진짜..눈물펑펑 반전에 반전 이런영화를 왜 영화관에서 못봤을까 ㅠㅠ', '긍정', '74.5%'],
 ['나름 아이들 용으로 좋아해 볼만함 하지만 아이들이 보기엔 다소 어려운 부분도 있음', '긍정', '67.16%'],
 ['너무좋네요^^ 한국에 대해 잘 알 수 있는 기회가 되어서 정말 좋았어요^^ 감사합니다~', '긍정', '89.58%'],
 ['무섭지 아나요^_^', '긍정', '57.73%'],
 ['그냥 김옥빈이 싫으므로...', '부정', '87.15%'],
 ['이 영화면 즐기고 느끼면된다. 따질필요없다. 느끼면 충분하다.', '긍정', '58.43%'],
 ['참...내용없다', '부정', '74.2%'],
 ['진짜 노오잼... 10자', '긍정', '67.95%'],
 ['뭐야이건 팽이쪼가리가 이그렇게쌤?ㅋㅋ', '부정', '62.22%'],
 ['전까지 잘 보던 프로였는데.이거 프로그램 진짜 폐지할라고 작정했습니까? 제 남자친구한테 자꾸 출연하라고 작가분들 돌아가면서 연락하시던데. 반년넘게 잘 만나고 있는 여자친구로써 상당히 기분 나쁩니다. 형제특집이니뭐니 그만 연락하세요. 조심하십시오 진짜.',
  '긍정',
  '54.99%'],
 ['제가 가장좋아하는 영화에요!!!너무너무 좋아요!!', '긍정', '81.6%'],
 ['내가 네이버 평점을 믿지 않게 해 준 고마운 영화들 중 하나지...', '부정', '60.57%'],
 ['무도를 건드리는건 심했다', '부정', '70.31%'],
 ['영화가 두서가 없고 난잡하다.', '부정', '74.2%'],
 ['잘 봤습니다.~~~..', '긍정', '67.47%'],
 ['아빠의 고통 그마음은 알겠으나 심하게지루해서 보다 잠든영화는 내평생 두번이내... 아무리 졸려도 영화가 재밌으면 잘보는대 이건뭐..거의 자장가수준.... 잠안올때 보면 잠잘올듯한 영화입니다.',
  '긍정',
  '52.16%'],
 ['떨어지는 긴장감과 번잡한 구성이 추진력을 잃게 했다', '부정', '51.17%'],
 ['국어책을 읽는 배우들과 함께 국어책을 읽는 신하균', '부정', '59.24%'],
 ['좋네요 ㅎ 1959년도 작입니다 ㅎ', '긍정', '85.86%'],
 ['매편볼때마다감동적이고교훈을배운것같아실패할수도잇는꿈에도전을다시하게되고희망도생기게된계기가되는드라마에요! 계속보고싶은드라마!',
  '긍정',
  '81.14%'],
 ['노잼영화다. 학교에서 봤는데 재미도 없고 몰입도 없고...', '부정', '82.14%'],
 ['초중반의 긴장감을 허무하게 만드는 억지스런 후반부', '부정', '65.81%'],
 ['머릿속 깊이 생각나는단어 이게 바로 전쟁이다!!', '긍정', '52.41%'],
 ['전형적으로 남녀주인공만 내세우고, 속이 텅텅빈 영화. 베니스 홍보용으로 쓸거면 아예 멋드러지게 그리던가. 10년전도 아니고 2010년에 촌스럽게 이런 영화 만들면 쓰것습니까~~ 졸리언니 역시 섹시하고 멋있네, 하고 대충보다보면 영화 끝남',
  '부정',
  '79.8%'],
 ['네이버 정신나갔냐? 이 영화가 왜 성인영화야', '부정', '79.3%'],
 ['아 끔찍하다 진짜 영화보면서 이렇게 시간아까운거 오랜만이네 재미도 없고 연기? 연기는 건담 오타쿠나오는 그 사람만잘하더만',
  '부정',
  '83.79%'],
 ["나를 설레게했다 아리게했다하더니 마지막엔 '둥'하고 큰 울림마저 준 고마운 영화.", '긍정', '65.97%'],
 ['사랑스러운영화...', '긍정', '65.91%'],
 ['욕나옴...입체영상 쥑임 아오...돈아까워서 억지봄 주인공들 차안에서만 찰영함 참어이없네', '부정', '90.4%'],
 ['정말 이러시면 안되는거잖아요.. ─━,,──━ㆀ', '부정', '51.55%'],
 ['최고다아아ㅏ아ㅏ아아아우어ㅓ오', '긍정', '61.15%'],
 ['내용 떠나서 제작진 해명이나 대응조차도 수준낮던데 뭐', '부정', '63.11%'],
 ['암만 봐도 007 시리즈의 패러디 같은데, 주인공, 악당, 스토리 등 영화의 대부분은 첩보 영화와 패러디 사이를 갈팡질팡 헤맨다. 첩보 영화로 보기엔 너무 가볍고, 패러디로 보기엔 너무 진지하다. 거기다 무척 지루하다.',
  '부정',
  '68.04%'],
 ['볼수록 빠져들게 하는 명화', '긍정', '60.1%'],

In [22]:
pd.DataFrame(data, columns = ['review', 'Pred', 'Prob']).head()

                                    review Pred    Prob
0                     최고의 sf 영화... 말이 필요없다   긍정  91.36%
1  귀엽고재밌었어요!!! 2005년에는 내용이 아직 받아들이기 힘들었나봐용   긍정  75.11%
2           99분의 시간이 짧음에도 불구하고 지루함이 느껴진다..   부정  67.52%
3                      사스가...노무라 만사이 최고의영화   긍정  89.33%
4                다시보고싶은영화,여러군데 찾아다녀도 없네ㅠ.ㅠ   긍정  58.49%

In [23]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.75      0.77      0.76       400
           1       0.77      0.74      0.75       400

    accuracy                           0.76       800
   macro avg       0.76      0.76      0.76       800
weighted avg       0.76      0.76      0.76       800

- 네이버 개발자센터를 이용해서 데이터를 수집
- 수집된 데이터를 이용하여 감정 평가 예측
    1. 네이버 개발자센터 접속
    2. 서비스 api 신청
    3. 서비스키를 이용해서 뉴스 데이터를 로드
    4. 데이터를 이용하여 감정분석

In [37]:
import os
from dotenv import load_dotenv
import requests
import re

In [38]:
load_dotenv()

True

In [39]:
naver_id = os.getenv('naver_api_id')
naver_secret = os.getenv('naver_api_secret')

In [40]:
naver_id

'iEbfZAMk4A7Fk60VGAmB'

In [41]:
# 네이버 api를 활용해서 news 제목들을 수집
url = "https://openapi.naver.com/v1/search/news.json"

params = {
    'query' : '왕사남',
    'display' : 30
}

headers = {
    'X-Naver-Client-Id' : naver_id,
    'X-Naver-Client-Secret' : naver_secret
}

res = requests.get(
    url,
    params = params,
    headers = headers
)
res

1. res.json()에서 title 부분의 value를 추출하여 하나의 리스트로 생성
2. <b>, </b> 문자를 제거
3. 위에서 만들어둔 벡터화를 이용하여 벡터화 작업
4. 로지스틱 모델을 이용하여 예측
5. 예측값과 확률을 데이터 프레임으로 생성

In [42]:
new_titles = []
for item in res.json()['items']:
    # item -> dict 형태 데이터가 대입
    # print(itme['title'].replace('<b>', '').replace('</b>', ''))
    # break
    clean_title = re.sub(r'<[^>]*>', '', item['title'])
    # print(clean_title)
    new_titles.append(clean_title)

In [43]:
X_api = tfidf_vec.transform(new_titles)

In [44]:
X_api.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(30, 3905))

In [45]:
pred_api = model.predict(X_api)
proba_api = model.predict_proba(X_api)

In [49]:
data = []
for title, value, proba in zip(new_titles, pred_api, proba_api):
    value = '긍정' if value == 1 else '부정'
    proba = round(max(proba)*100, 2)
    data.append({
        'title' : title,
        'pred' : value,
        'pred_proba' : proba
    })
df_api = pd.DataFrame(data)

In [51]:
df_api.sort_values('pred_proba', ascending = False).head(10)

                                           title pred  pred_proba
2                    ‘호프’ 찍은 해남에 ‘1970년대 거리’ 만든다   부정       76.54
22  [더벨][매니저 프로파일 | 쏠레어파트너스] 영화 현장 20년, 시나리오서...   부정       67.70
29        ‘군체’, ‘왕사남’보다 빠르다…10일 만에 300만 손익분기점 돌파   긍정       62.89
5               밀양시, 얼음골 방문 인증 SNS 이벤트 6월 한달간 진행   부정       62.64
25       “‘왕사남’보다 빠르다, 올해 개봉작 중 1등”…‘군체’ 310만 돌파   긍정       60.54
17          연상호 감독 '군체', 400만 향해 돌진 중-'왕사남' 넘을까?   부정       60.04
26           ‘군체’ 벌써 300만 돌파, ‘왕사남’보다 빠르다 [지금뉴스]   긍정       59.61
16         한강이 연 ‘소설의 시대’ 여전 …상반기 베스트셀러 1~3위 휩쓸어   부정       59.51
7   '왕사남' 열풍에 찻사발축제 효과 '톡톡'…문경새재 방문객 153만 명 돌...   부정       59.33
24        연간 2위 '군체', 350만명 최단기 기록…'왕사남'보다 2일 빨라   긍정       58.59

#### 모델의 성능을 올려보자
- 실제 모델의 성능
    - 정확도 : 77%
- 모델의 성능을 올릴수 있는 방법
    - 데이터 양을 늘린다
    - 전처리 방법을 다른 방법으로 사용 (분석기, 벡터화)
    - 스케일러를 이용
    - 벡터화 모델과 분류 모델의 파라미터 수정
    - 모델을 변경

In [ ]:
from sklearn.preprocessing import MaxAbsScaler
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.pipeline import Pipeline

In [ ]:
ma_scaler = MaxAbsScaler()
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
pipe = Pipeline(
    [
        (
            'vec', tfidf_vec
        ), 
        {
            'scaler', ma_scaler
        }, 
        (
            'model', model
        )
    ]
)

In [ ]:
# 파라미터 조합 생성 
params = {
    'vec__min_df' : [2, 3], 
    'vec__ngram_range' : [ (1, 2), (1, 1) ], 
    'vec__max_features' : [ None, 1000 ], 
    'model__C' : [0.8, 0.9, 1.0], 
}

In [ ]:
grid = GridSearchCV(
    estimator = pipe, 
    param_grid = params, 
    cv = cv, 
    verbose=1
)

In [ ]:
grid.fit(X, y)

In [ ]:
grid.best_params_

In [ ]:
pred_api = grid.predict(new_titles)
proba_api = grid.predict_proba(new_titles)

In [ ]:
data = []
for title, value, proba in zip(new_titles, pred_api, proba_api):
    value = '긍정' if value == 1 else '부정'
    proba = round( max(proba) * 100, 2 )
    data.append( 
        {
            'title' : title, 
            'pred' : value, 
            'pred_proba' : proba
        }
    )

df_api = pd.DataFrame(data)

In [ ]:
df_api.head(10)

In [ ]:
load_dotenv()

In [ ]:
youtube_api = os.getenv('youtube_api')

- 유튜브에서 특정 영상의 댓글을 로드
    - 구글 클라우드 콘솔에서 api를 신청
    - 신청이 된 api key와 영상의 id 값이 필요
    - 라이브러리 설치
    - google-api-python-client 라이브러리 설치

In [ ]:
# !pip install google-api-python-client

Collecting google-api-python-client
  Downloading google_api_python_client-2.197.0-py3-none-any.whl.metadata (7.0 kB)
Collecting httplib2<1.0.0,>=0.19.0 (from google-api-python-client)
  Downloading httplib2-0.31.2-py3-none-any.whl.metadata (2.2 kB)
Collecting google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0 (from google-api-python-client)
  Downloading google_auth-2.53.0-py3-none-any.whl.metadata (5.5 kB)
Collecting google-auth-httplib2<1.0.0,>=0.2.0 (from google-api-python-client)
  Downloading google_auth_httplib2-0.4.0-py3-none-any.whl.metadata (3.0 kB)
Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 (from google-api-python-client)
  Downloading google_api_core-2.31.0-py3-none-any.whl.metadata (3.2 kB)
Collecting uritemplate<5,>=3.0.1 (from google-api-python-client)
  Downloading uritemplate-4.2.0-py3-none-any.whl.metadata (2.6 kB)
Collecting googleapis-common-protos<2.0.0,>=1.63.2 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client)
  Downloading googleapis_common_protos-1.75.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: protobuf<8.0.0,>=5.29.6 in c:\python310\lib\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (7.34.1)
Collecting proto-plus<2.0.0,>=1.24.0 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client)
  Downloading proto_plus-1.28.0-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: requests<3.0.0,>=2.33.0 in c:\python310\lib\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.33.1)
Collecting pyasn1-modules>=0.2.1 (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client)
  Downloading pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: cryptography>=38.0.3 in c:\python310\lib\site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (46.0.7)
Requirement already satisfied: pyparsing<4,>=3.1 in c:\python310\lib\site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client) (3.3.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\python310\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\python310\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\python310\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\python310\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2026.2.25)
Requirement already satisfied: cffi>=2.0.0 in c:\python310\lib\site-packages (from cryptography>=38.0.3->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (2.0.0)
Requirement already satisfied: typing-extensions>=4.13.2 in c:\users\신재호\appdata\roaming\python\python310\site-packages (from cryptography>=38.0.3->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (4.15.0)
Requirement already satisfied: pycparser in c:\python310\lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (3.0)
Collecting pyasn1<0.7.0,>=0.6.1 (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client)
  Downloading pyasn1-0.6.3-py3-none-any.whl.metadata (8.4 kB)
Downloading google_api_python_client-2.197.0-py3-none-any.whl (15.3 MB)
   ---------------------------------------- 0.0/15.3 MB ? eta -:--:--
   ------------------------- -------------- 9.7/15.3 MB 50.5 MB/s eta 0:00:01
   ---------------------------------------- 15.3/15.3 MB 43.8 MB/s  0:00:00
Downloading google_api_core-2.31.0-py3-none-any.whl (173 kB)
Downloading google_auth-2.53.0-py3-none-any.whl (246 kB)
Downloading google_auth_httplib2-0.4.0-py3-none-any.whl (9.5 kB)
Downloading googleapis_common_protos-1.75.0-py3-none-any.whl (300 kB)
Downloading httplib2-0.31.2-py3-none-any.whl (91 kB)
Downloading proto_plus-1.28.0-py3-none-any.whl (50 kB)
Downloading uritemplate-4.2.0-py3-none-any.whl (11 kB)
Downloading pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
Downloading pyasn1-0.6.3-py3-none-any.whl (83 kB)
Installing collected packages: uritemplate, pyasn1, proto-plus, httplib2, googleapis-common-protos, pyasn1-modules, google-auth, google-auth-httplib2, google-api-core, google-api-python-client

   ---- -----------------------------------  1/10 [pyasn1]
   ---- -----------------------------------  1/10 [pyasn1]
   ---- -----------------------------------  1/10 [pyasn1]
   ---- -----------------------------------  1/10 [pyasn1]
   ---- -----------------------------------  1/10 [pyasn1]
   -------- -------------------------------  2/10 [proto-plus]
   -------- -------------------------------  2/10 [proto-plus]
   -------- -------------------------------  2/10 [proto-plus]
   -------- -------------------------------  2/10 [proto-plus]
   ---------------- -----------------------  4/10 [googleapis-common-protos]
   ---------------- -----------------------  4/10 [googleapis-common-protos]
   ---------------- -----------------------  4/10 [googleapis-common-protos]
   ---------------- -----------------------  4/10 [googleapis-common-protos]
   ---------------- -----------------------  4/10 [googleapis-common-protos]
   ---------------- -----------------------  4/10 [googleapis-common-protos]
   ---------------- -----------------------  4/10 [googleapis-common-protos]
   ---------------- -----------------------  4/10 [googleapis-common-protos]
   ---------------- -----------------------  4/10 [googleapis-common-protos]
   ---------------- -----------------------  4/10 [googleapis-common-protos]
   ---------------- -----------------------  4/10 [googleapis-common-protos]
   ---------------- -----------------------  4/10 [googleapis-common-protos]
   ---------------- -----------------------  4/10 [googleapis-common-protos]
   ---------------- -----------------------  4/10 [googleapis-common-protos]
   -------------------- -------------------  5/10 [pyasn1-modules]
   -------------------- -------------------  5/10 [pyasn1-modules]
   -------------------- -------------------  5/10 [pyasn1-modules]
   -------------------- -------------------  5/10 [pyasn1-modules]
   -------------------- -------------------  5/10 [pyasn1-modules]
   -------------------- -------------------  5/10 [pyasn1-modules]
   -------------------- -------------------  5/10 [pyasn1-modules]
   -------------------- -------------------  5/10 [pyasn1-modules]
   -------------------- -------------------  5/10 [pyasn1-modules]
   -------------------- -------------------  5/10 [pyasn1-modules]
   -------------------- -------------------  5/10 [pyasn1-modules]
   -------------------- -------------------  5/10 [pyasn1-modules]
   -------------------- -------------------  5/10 [pyasn1-modules]
   -------------------- -------------------  5/10 [pyasn1-modules]
   -------------------- -------------------  5/10 [pyasn1-modules]
   -------------------- -------------------  5/10 [pyasn1-modules]
   ------------------------ ---------------  6/10 [google-auth]
   ------------------------ ---------------  6/10 [google-auth]
   ------------------------ ---------------  6/10 [google-auth]
   ------------------------ ---------------  6/10 [google-auth]
   ------------------------ ---------------  6/10 [google-auth]
   ------------------------ ---------------  6/10 [google-auth]
   ------------------------ ---------------  6/10 [google-auth]
   ------------------------ ---------------  6/10 [google-auth]
   ------------------------ ---------------  6/10 [google-auth]
   ------------------------ ---------------  6/10 [google-auth]
   ------------------------ ---------------  6/10 [google-auth]
   -------------------------------- -------  8/10 [google-api-core]
   -------------------------------- -------  8/10 [google-api-core]
   -------------------------------- -------  8/10 [google-api-core]
   -------------------------------- -------  8/10 [google-api-core]
   -------------------------------- -------  8/10 [google-api-core]
   -------------------------------- -------  8/10 [google-api-core]
   -------------------------------- -------  8/10 [google-api-core]
   -------------------------------- -------  8/10 [google-api-core]
   ------------------------------------ ---  9/10 [google-api-python-client]
   ------------------------------------ ---  9/10 [google-api-python-client]
   ------------------------------------ ---  9/10 [google-api-python-client]
   ------------------------------------ ---  9/10 [google-api-python-client]
   ------------------------------------ ---  9/10 [google-api-python-client]
   ------------------------------------ ---  9/10 [google-api-python-client]
   ------------------------------------ ---  9/10 [google-api-python-client]
   ------------------------------------ ---  9/10 [google-api-python-client]
   ------------------------------------ ---  9/10 [google-api-python-client]
   ------------------------------------ ---  9/10 [google-api-python-client]
   ------------------------------------ ---  9/10 [google-api-python-client]
   ------------------------------------ ---  9/10 [google-api-python-client]
   ---------------------------------------- 10/10 [google-api-python-client]

Successfully installed google-api-core-2.31.0 google-api-python-client-2.197.0 google-auth-2.53.0 google-auth-httplib2-0.4.0 googleapis-common-protos-1.75.0 httplib2-0.31.2 proto-plus-1.28.0 pyasn1-0.6.3 pyasn1-modules-0.4.2 uritemplate-4.2.0

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# !pip install google-api-python-client
# 영상의 id를 하나 복사
# 유튜브 영상 url에서 가장 마지막 v=ID
video_id = 'z8BW9Fo9-wE'

In [ ]:
from googleapiclient.discovery import build

In [ ]:
youtube = build('youtube', 'v3', developerKey=youtube_api)

In [ ]:
request = youtube.commentThreads().list(
    part = 'snippet', 
    videoId = video_id, 
    maxResults = 10, 
    textFormat = 'plainText'
)

In [ ]:
res = request.execute()

In [ ]:
from pprint import pprint

In [ ]:
comment = []
for item in res['items']:
    comment.append(item['snippet']['topLevelComment']['snippet']['textDisplay'])
    # break

In [ ]:
comment

In [ ]:
labels = [0, 0, 0, 0, 1, 1, 1, 0, 0, 1]
commnet_df = pd.DataFrame(zip(comment, labels), columns = ['review', 'label'])
commnet_df

In [ ]:
pred = grid.predict(comment)
pred_proba = grid.predict_proba(comment)

In [ ]:
pred

In [ ]:
print(classification_report(pred, labels))

In [ ]:
data = []
for review, label, value, proba in zip(comment, labels, pred, pred_proba):
    label = '긍정' if label == 1 else '부정'
    value = '긍정' if value == 1 else '부정'
    proba = round( max(proba) * 100 , 2)
    proba = str(proba) + '%'

    data.append(
        {
            'review' : review, 
            'origin' : label, 
            'pred' : value, 
            'proba' : proba
        }
    )

df_youtube = pd.DataFrame(data)
df_youtube