#### XGBoost
- 부스팅 중 대표적인 모델 
- Gradient Boosting 알고리즘을 고도화한 모델 
- 빠른 속도, 높은 성능, 과적합 제어 기능을 제공하는 트리 기반 앙상블 모델 
- XGBoost는 sklearn에 포함되어 있지 않다. (별도의 설치가 필요)
- 분류, 회귀 모델 모두 존재 
- 부스팅의 단점인 병렬화의 어려움을 어느정도 해결한 알고리즘( 피쳐 별 조건식을 생성하는데 cpu를 병렬로 사용 )

- parameter
    1. 학습 제어 관련
        - n_estimators
            - 기본값 : 100
            - 트리가 생성이 되는 개수
            - 클수록 성능이 올라가지만 계산이 많아지면서 시간은 증가
        - learning_rate
            - 기본값 : 0.3
            - 각 단계별 학습율(기여도)
            - 일반적으로는 0.01 ~ 0.3
            - 작을수록 데이터의 단순화, 클수록 복잡
        - early_stopping_rounds
            - 기본값 : None
            - fit() 함수에서 'eval_set' 매개변수에서 지정된 검증용 데이터셋을 이용한 평가 지표가 n라운드 연속 개선이 되지 않은 경우 학습을 중단 
            - int형 입력값
            - n_estimators 배개변수의 값을 크게 잡고 이 값으로 최적의 라운드를 검색 
        - objective 
            - 손실함수 지정
            - 분류 
                - "binary:logistic"
                    - 이진 분류용
                    - 출력 : 확률
                    - 시그모이드 함수를 이용하여 확률 형태
                - "binary:logiraw"
                    - 이진 분류용
                    - 출력 : log-odds 값(확률x)
                - "multi:softmax"
                    - 다중 클래스 분류 
                    - 출력 : 각 클래스의 인덱스(정수)
                - "multi:softprob"
                    - 다중 클래스 분류
                    - 출력 : 각 클래스별 확률
            - 회귀
                - "reg:squarederror"
                    - 평균 제곱 오차(MSE) 기반 
                    - 연속형 데이터 예측 사용
                - "reg:absoluteerror"
                    - 평균 절대 오차(MAE) 기반
                    - 이상치 데이터에 대해서 유리 
                - "reg:squaredlogerror"
                    - 로그 평균 제곱 오차(MSLE) 기반
                    - 종속 데이터가 양수이고 값의 범위가 매우 넓은 경우 유리
        - eval_metric
            - 기본값 : None
            - 검증 시 사용할 평가 지표
            - 조기 종료(early_stopping_rounds)와 함께 사용
            - 분류 : "logloss", "auc", "error" ( 다중분류 'm' -> 'mlogloss' )
            - 회귀 : 'rmse', 'mae' 등등
    2. 트리 구조 제어 
        - max_depth
            - 기본값 : 6
            - 트리의 최대 깊이를 지정 
            - 일반적으로 3~10정도를 사용
        - min_child_weight
            - 기본값 : 1.0
            - leaf가 분할되기 위한 최소한의 가중치 
            - 값이 커지면 보수적인 분할(과적합의 위험성 내려감)
        - gamma
            - 기본값 : 0.0
            - leaf 추가 분할에 필요한 최소 손실 감소
            - 값이 커지면 불필요한 분할 억제 
        - max_leaves
            - 기본값 : None
            - leaf node의 개수를 제한 
            - 깊이 대신 개수로 복잡도 제어 
    3. 샘플링 / 다양성 제어 
        - subsample
            - 기본값 : 1.0
            - 각 트리에서 학습에서 사용할 샘플의 비율
            - 일반적으로는 0.6 ~ 0.9 사용 -> 과적합 방지, 샘플의 다양성 
        - colsample_bytree
            - 기본값 : 1.0
            - 각 트리에서 학습에서 사용할 샘플의 피쳐의 비율
            - 일반적으로 0.5 ~ 0.9 사용
    4. 정규화 / 규제 (회귀)
        - reg_lambda
            - 기본값 : 1.0
            - L2 정규화(가중치의 크기를 억제)
            - 값이 큰 경우 안정적인 모델. 과적합 방지 
        - reg_alpha
            - 기본값 : 0.0
            - L1 정규화(가중치 희소화)
            - 피쳐의 선택 효과
            - 고차원 데이터에서 사용
    5. 데이터 불균형 처리 (분류)
        - scale_pos_weight
            - 기본값 : 1
            - 양성(1) / 음성(0) 클래스의 불균형 보장
            - neg / pos 비율로 설정 (음성 90%, 양성 10% -> 9)
    6. 실행의 최적화
        - tree_method
            - 기본값 : 'auto'
            - 'auto' : 자동선택
            - "hist" : 대규모 데이터 빠른학습
            - "gpu_hist" : GPU 가속 -> 대규모 / 고차원 데이터에서 권장 
        - max_bin
            - 기본값 = 256
            - 히스토그램의 버킷(구간)의 수를 지정 
            - 값이 커지면 정확도가 올라가지만 메모리의 사용량과 시간 증가 
    - 하이퍼 파라미터 튜닝의 일반적인 순서 
        1. 1순위 ( 모델 성능 )
            - n_estimator(트리의 개수), learning_rate(기여도)
            - max_depth(최대 깊이)
            - min_child_weight(최소 가중치의 합)
        2. 2순위 (과적합 / 일반화)
            - gamma(손실)
            - subsample(학습에 사용할 데이터의 비율)
            - colsample_bytree(학습에 사용할 피쳐의 비율)
        3. 3순위 (세밀한 조정 / 특수 케이스)\
            - reg_lambda, reg_alpha(정규화)
            - scale_pos_weight(데이터 불균형)
            - tree_method, max_bin(실행 최적화)
- 속성 
    - feature_inportances_
        - 학습된 모델의 피쳐들의 중요도
    - best_score, best_iteration, best_n_tree_rounds
        - 조기 종료 이용시에 사용 가능한 속성
        - 최적의 결과 값들을 보여줌
    - eval_result
        - 학습 중 평가 지표 기록
    - classes_
        - 학습된 클래스의 목록
    - n_features_in_
        - 입력된 피쳐의 수
- 메서드 
    - fit(X, y, options)
        - 모델에 학습 ( 학습 횟수(에폭)마다 검증이 가능 ) 
        - options 매개변수
            - eval_set 
                - 검증 데이터셋 지정 
                - 학습 로그와 조기 종료에서 사용
            - verbose
                - 기본값 : None
                - True : 각 라운드마다의 성능 출력 
                - 10(int) : 10라운드마다 성능을 출력 
    - predict(X)
        - 모델의 예측
    - socre(X, y)
        - 분류 : 정확도
        - 회귀 : R2score
    - save_model(filename) / load_model(filename)
        - 모델을 저장하거나 불러오기

In [ ]:
# 라이브러리 설치 
# !pip install xgboost

In [1]:
from xgboost import XGBClassifier, XGBRegressor
from sklearn.model_selection import train_test_split
import pandas as pd 
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report, \
        mean_squared_error, r2_score

In [2]:
body = pd.read_csv("../data/bodyPerformance.csv")

In [3]:
# 성별 / 등급을 수치형 데이터로 변환 
body['gender'] = np.where(
    body['gender'] == 'M', 0, 1
)

body['class'] = body['class'].map(
    {
        'A' : 0, 
        'B' : 1, 
        'C' : 2, 
        'D' : 3
    }
)

body.head()

,age,gender,height_cm,weight_kg,body fat_%,diastolic,systolic,gripForce,sit and bend forward_cm,sit-ups counts,broad jump_cm,class
0,27.0,0,172.3,75.24,21.3,80.0,130.0,54.9,18.4,60.0,217.0,2
1,25.0,0,165.0,55.80,15.7,77.0,126.0,36.4,16.3,53.0,229.0,0
2,31.0,0,179.6,78.00,20.1,92.0,152.0,44.8,12.0,49.0,181.0,2
3,32.0,0,174.5,71.10,18.4,76.0,147.0,41.4,15.2,53.0,219.0,1
4,28.0,0,173.8,67.70,17.1,70.0,127.0,43.5,27.1,45.0,217.0,1

In [4]:
x = body.drop('class', axis=1)
y = body['class']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=42, stratify=y
)

In [6]:
# validation / test로 데이터셋을 나눠준다. 
X_vali, X_test, y_vali, y_test = train_test_split(
    X_test, y_test, test_size=0.5, random_state=42, stratify=y_test
)

In [7]:
# XGBoost 분류 모델을 생성 (다중 분류 모델 -> softmax 기반)
clf = XGBClassifier(
    n_estimators = 1000, 
    learning_rate = 0.05, 
    objective = 'multi:softprob', 
    eval_metric = 'mlogloss', 
    max_depth = 5, 
    min_child_weight = 2, 
    subsample = 0.8, 
    colsample_bytree = 0.8, 
    early_stopping_rounds = 50, 
    random_state = 42, 
    tree_method = 'hist'
)

In [8]:
# 모델에 학습 및 검증 
clf.fit(
    X_train, y_train, 
    eval_set = [(X_vali, y_vali)], verbose = 50
)

[0]	validation_0-mlogloss:1.35525
[50]	validation_0-mlogloss:0.84301
[100]	validation_0-mlogloss:0.73383
[150]	validation_0-mlogloss:0.68888
[200]	validation_0-mlogloss:0.66614
[250]	validation_0-mlogloss:0.65273
[300]	validation_0-mlogloss:0.64388
[350]	validation_0-mlogloss:0.63908
[400]	validation_0-mlogloss:0.63424
[450]	validation_0-mlogloss:0.63262
[500]	validation_0-mlogloss:0.63244
[550]	validation_0-mlogloss:0.63176
[582]	validation_0-mlogloss:0.63163

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=50,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=2, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=1000, n_jobs=None,
              num_parallel_tree=None, ...)

In [9]:
# 가장 성능이 좋은 횟수는 언제인가?
print("Bsst Iteration : ", clf.best_iteration)
print("Best Score : ", clf.best_score)

Bsst Iteration :  532
Best Score :  0.6311029217361982

In [10]:
# 실제 예측 
clf_pred = clf.predict(X_test)

In [11]:
print(confusion_matrix(y_test, clf_pred))

print(classification_report(y_test, clf_pred))

[[456  43   3   0]
 [115 310  63  14]
 [ 43  91 352  17]
 [  7  22  48 425]]
              precision    recall  f1-score   support

           0       0.73      0.91      0.81       502
           1       0.67      0.62      0.64       502
           2       0.76      0.70      0.73       503
           3       0.93      0.85      0.89       502

    accuracy                           0.77      2009
   macro avg       0.77      0.77      0.77      2009
weighted avg       0.77      0.77      0.77      2009

In [12]:
# boston 데이터를 로드 
boston = pd.read_csv("../csv/boston.csv")

In [13]:
boston.head(1)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.09,1.0,296.0,15.3,396.9,4.98,24.0

In [14]:
boston.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  Price    506 non-null    float64
dtypes: float64(14)
memory usage: 55.5 KB

In [15]:
x = boston.drop('Price', axis=1)
y = boston['Price']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [17]:
# XGBoost 회귀 모델 생성 
reg = XGBRegressor(
    random_state = 42, 
    n_estimators = 1000, 
    learining_rate = 0.01, 
    subsample = 1, 
    colsample_bytree = 1, 
    max_depth = 10, 
    reg_lambda = 1.0, 
    early_stopping_rounds = 100, 
    objective = 'reg:squarederror', 
    min_child_wight = 3
)

In [18]:
reg.fit(X_train, y_train, 
        eval_set = [ (X_test, y_test)], verbose = 50 
        )

[0]	validation_0-rmse:6.71530

c:\Python310\lib\site-packages\xgboost\callback.py:385: UserWarning: [23:51:08] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "learining_rate", "min_child_wight" } are not used.

  self.starting_round = model.num_boosted_rounds()

[50]	validation_0-rmse:3.01960
[100]	validation_0-rmse:3.01920
[150]	validation_0-rmse:3.01920
[163]	validation_0-rmse:3.01920

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None, colsample_bytree=1,
             device=None, early_stopping_rounds=100, enable_categorical=False,
             eval_metric=None, feature_types=None, feature_weights=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learining_rate=0.01,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=10,
             max_leaves=None, min_child_weight=None, min_child_wight=3,
             missing=nan, monotone_constraints=None, multi_strategy=None,
             n_estimators=1000, ...)

In [19]:
reg_pred = reg.predict(X_test)

In [20]:
print(reg.best_iteration)
print("MSE : ", mean_squared_error(y_test, reg_pred))
print("R2 : ", r2_score(y_test, reg_pred) )

63
MSE :  9.115319730397161
R2 :  0.8757009479455169