In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_squared_log_error, \
                            root_mean_squared_error, mean_absolute_percentage_error, r2_score

In [2]:
boston = pd.read_csv('../csv/boston.csv')
boston.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2

In [3]:
boston.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  Price    506 non-null    float64
dtypes: float64(14)
memory usage: 55.5 KB

In [4]:
X = boston.drop(['CHAS', 'Price'], axis = 1)
X.head()

,CRIM,ZN,INDUS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33

In [5]:
cols = boston.columns.difference(['CHAS', 'Price'])

In [6]:
X.describe()

,CRIM,ZN,INDUS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063
std,8.601545,23.322453,6.860353,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062
min,0.006320,0.000000,0.460000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000
25%,0.082045,0.000000,5.190000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000
50%,0.256510,0.000000,9.690000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000
75%,3.677083,12.500000,18.100000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000
max,88.976200,100.000000,27.740000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000

In [7]:
y = boston['Price']

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42
)

In [10]:
X_train

,CRIM,ZN,INDUS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
477,15.02340,0.0,18.10,0.6140,5.304,97.3,2.1007,24.0,666.0,20.2,349.48,24.91
15,0.62739,0.0,8.14,0.5380,5.834,56.5,4.4986,4.0,307.0,21.0,395.62,8.47
332,0.03466,35.0,6.06,0.4379,6.031,23.3,6.6407,1.0,304.0,16.9,362.25,7.83
423,7.05042,0.0,18.10,0.6140,6.103,85.1,2.0218,24.0,666.0,20.2,2.52,23.29
19,0.72580,0.0,8.14,0.5380,5.727,69.5,3.7965,4.0,307.0,21.0,390.95,11.28
...,...,...,...,...,...,...,...,...,...,...,...,...
106,0.17120,0.0,8.56,0.5200,5.836,91.9,2.2110,5.0,384.0,20.9,395.67,18.66
270,0.29916,20.0,6.96,0.4640,5.856,42.1,4.4290,3.0,223.0,18.6,388.65,13.00
348,0.01501,80.0,2.01,0.4350,6.635,29.7,8.3440,4.0,280.0,17.0,390.94,5.99
435,11.16040,0.0,18.10,0.7400,6.629,94.6,2.1247,24.0,666.0,20.2,109.85,23.27
102,0.22876,0.0,8.56,0.5200,6.405,85.4,2.7147,5.0,384.0,20.9,70.80,10.63

In [11]:
y_train

477    12.0
15     19.9
332    19.4
423    13.4
19     18.2
       ...
106    19.5
270    21.1
348    24.5
435    13.4
102    18.6
Name: Price, Length: 404, dtype: float64

In [12]:
print(y_train.mean())
print(y_test.mean())

22.796534653465343
21.488235294117644

In [13]:
lr = LinearRegression()

In [14]:
lr.fit(X_train, y_train)

LinearRegression()

In [15]:
pred = lr.predict(X_test)

In [16]:
pred

array([29.21866014, 33.5514672 , 14.81065799, 25.08472546, 19.17392702,
       23.28640399, 17.7441225 , 14.46092123, 23.30259107, 20.75647992,
       22.45317074, 18.77736488, -6.52970935, 21.74968493, 19.30195869,
       26.59522081, 21.21754878,  5.84256345, 40.88127145, 17.98690048,
       27.43177299, 30.29871753, 11.20759373, 24.39691543, 18.24007254,
       16.01087618, 22.79683608, 14.7395835 , 19.75576272, 19.29298669,
       22.52017326, 25.37983983, 26.36505651, 18.2369769 , 16.93419024,
       17.55836756, 31.50335902, 20.24159576, 21.08251444, 24.65267564,
       13.90452083, 32.57892685, 43.16818646, 17.12896113, 27.36706026,
       17.35854092, 14.01099631, 25.95229584, 20.56538298, 30.1790087 ,
       21.49771119, 34.68242963, 16.02334401, 26.33533751, 40.12023825,
       22.90083215, 19.30066018, 32.99670513, 25.11269667, 12.73224637,
       22.79239332, 30.71175958, 31.81487172, 15.82826036, 20.05819836,
       13.90910292, 20.92057234, 26.01802251, 30.8047209 , 11.73369775,
       20.50842276, 27.85098594, 11.20111241, 15.49838312, 23.81749186,
        6.14293872, 21.62836904, 41.88626638, 19.04288451,  8.71754251,
       20.7149105 , 13.32176762, 20.65818567,  9.52638634, 23.44962479,
       29.40116944, 19.46566931, 25.67438034, 29.40908719, 20.44020289,
       25.70799403,  5.59199842, 20.41059108, 14.70093463, 12.90622241,
       21.06007823, 25.17368387, -0.52045268, 13.85769946, 16.19518173,
       22.24816901, 24.52416597])

In [17]:
y_test

173    23.6
274    32.4
491    13.6
72     22.8
452    16.1
       ...
412    17.9
436     9.6
411    17.2
86     22.5
75     21.4
Name: Price, Length: 102, dtype: float64

In [18]:
price_df = pd.DataFrame(pred, columns = ['pred price'])
price_df['actual price'] = y_test.values

price_df

     pred price  actual price
0     29.218660          23.6
1     33.551467          32.4
2     14.810658          13.6
3     25.084725          22.8
4     19.173927          16.1
..          ...           ...
97    -0.520453          17.9
98    13.857699           9.6
99    16.195182          17.2
100   22.248169          22.5
101   24.524166          21.4

[102 rows x 2 columns]

In [21]:
price_df['error'] = price_df['actual price'] - price_df['pred price']

In [22]:
price_df

     pred price  actual price      error
0     29.218660          23.6  -5.618660
1     33.551467          32.4  -1.151467
2     14.810658          13.6  -1.210658
3     25.084725          22.8  -2.284725
4     19.173927          16.1  -3.073927
..          ...           ...        ...
97    -0.520453          17.9  18.420453
98    13.857699           9.6  -4.257699
99    16.195182          17.2   1.004818
100   22.248169          22.5   0.251831
101   24.524166          21.4  -3.124166

[102 rows x 3 columns]

In [23]:
mae = mean_absolute_error(y_test, pred)
mse = mean_squared_error(y_test, pred)
rmse = root_mean_squared_error(y_test, pred)

print(f'MAE : {round(mae, 2)}')
print(f'MSE : {round(mse, 2)}')
print(f'RMSE : {round(rmse, 2)}')

MAE : 3.24
MSE : 24.64
RMSE : 4.96

In [24]:
r2 = r2_score(y_test, pred)
print(f'R2 Score : {round(r2, 2)}')

R2 Score : 0.66

In [25]:
boston.corr().sort_values('Price')

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
LSTAT,0.455621,-0.412995,0.603800,-0.053929,0.590879,-0.613808,0.602339,-0.496996,0.488676,0.543993,0.374044,-0.366087,1.000000,-0.737663
PTRATIO,0.289946,-0.391679,0.383248,-0.121515,0.188933,-0.355501,0.261515,-0.232471,0.464741,0.460853,1.000000,-0.177383,0.374044,-0.507787
INDUS,0.406583,-0.533828,1.000000,0.062938,0.763651,-0.391676,0.644779,-0.708027,0.595129,0.720760,0.383248,-0.356977,0.603800,-0.483725
TAX,0.582764,-0.314563,0.720760,-0.035587,0.668023,-0.292048,0.506456,-0.534432,0.910228,1.000000,0.460853,-0.441808,0.543993,-0.468536
NOX,0.420972,-0.516604,0.763651,0.091203,1.000000,-0.302188,0.731470,-0.769230,0.611441,0.668023,0.188933,-0.380051,0.590879,-0.427321
CRIM,1.000000,-0.200469,0.406583,-0.055892,0.420972,-0.219247,0.352734,-0.379670,0.625505,0.582764,0.289946,-0.385064,0.455621,-0.388305
RAD,0.625505,-0.311948,0.595129,-0.007368,0.611441,-0.209847,0.456022,-0.494588,1.000000,0.910228,0.464741,-0.444413,0.488676,-0.381626
AGE,0.352734,-0.569537,0.644779,0.086518,0.731470,-0.240265,1.000000,-0.747881,0.456022,0.506456,0.261515,-0.273534,0.602339,-0.376955
CHAS,-0.055892,-0.042697,0.062938,1.000000,0.091203,0.091251,0.086518,-0.099176,-0.007368,-0.035587,-0.121515,0.048788,-0.053929,0.175260
DIS,-0.379670,0.664408,-0.708027,-0.099176,-0.769230,0.205246,-0.747881,1.000000,-0.494588,-0.534432,-0.232471,0.291512,-0.496996,0.249929
B,-0.385064,0.175520,-0.356977,0.048788,-0.380051,0.128069,-0.273534,0.291512,-0.444413,-0.441808,-0.177383,1.000000,-0.366087,0.333461
ZN,-0.200469,1.000000,-0.533828,-0.042697,-0.516604,0.311991,-0.569537,0.664408,-0.311948,-0.314563,-0.391679,0.175520,-0.412995,0.360445
RM,-0.219247,0.311991,-0.391676,0.091251,-0.302188,1.000000,-0.240265,0.205246,-0.209847,-0.292048,-0.355501,0.128069,-0.613808,0.695360
Price,-0.388305,0.360445,-0.483725,0.175260,-0.427321,0.695360,-0.376955,0.249929,-0.381626,-0.468536,-0.507787,0.333461,-0.737663,1.000000